### ISSUE TITLE
 code error

### ISSUE THREAD

**Issue by MaiJiantian** [etherchina/solidity-doc-cn#107]
The delegate is wrong on line 86 of the voting case code.
it should be => sender.delegate = to;

**Comment by riversyang** [comment]
Your description is not very clear. Can you please make a pr for this? If not, please tell us which file/chapter you are talking about. Thanks.

**Comment by MaiJiantian** [comment]
File“solidity-by-example.rst” there is an error；
in “sender.delegate_ = to;”，Error in “delegate_ ”，it should be “delegate”

**Comment by riversyang** [comment]
Fixed. Thanks @MaiJiantian .
