### ISSUE TITLE
翻译introduction-to-smart-contracts.rst

### ISSUE THREAD

**Issue by hongbinzuo** [etherchina/solidity-doc-cn#20]

**Comment by buffalo2004** [comment]
试试，收到了吗

**Comment by ysqi** [comment]
@buffalo2004 请问在翻译中吗？该文章有被其他人 PR #7

**Comment by hongbinzuo** [comment]
http://solidity-cn.readthedocs.io/zh/latest/introduction-to-smart-contracts.html

<img width="751" alt="2018-03-09 10 34 28" src="https://user-images.githubusercontent.com/1685008/37187532-b19b316c-2385-11e8-95b3-199b8fee299a.png">
<img width="784" alt="2018-03-09 10 34 35" src="https://user-images.githubusercontent.com/1685008/37187533-b1d4de94-2385-11e8-8326-eeac2a78d8e5.png">
<img width="234" alt="2018-03-09 10 35 06" src="https://user-images.githubusercontent.com/1685008/37187534-b240e58a-2385-11e8-890f-b4ae81c05a17.png">

请调整上述格式。“存储，”的逗号建议换成“、”

**Comment by hongbinzuo** [comment]
<img width="713" alt="2018-03-09 10 44 42" src="https://user-images.githubusercontent.com/1685008/37187813-fa0966e8-2386-11e8-95c0-6cfd139d48a9.png">

“（实现”前面多了一个句号

**Comment by hongbinzuo** [comment]
<img width="659" alt="2018-03-09 10 48 45" src="https://user-images.githubusercontent.com/1685008/37187906-7d0332a4-2387-11e8-996e-9ed62348c8e2.png">

“如下所示”后面需要标点，统一用冒号或逗号

**Comment by hongbinzuo** [comment]
<img width="725" alt="2018-03-09 10 52 36" src="https://user-images.githubusercontent.com/1685008/37188012-0645200e-2388-11e8-878d-9f7f92a9391a.png">

标点请改为中文标点

**Comment by hongbinzuo** [comment]
<img width="722" alt="2018-03-09 10 54 50" src="https://user-images.githubusercontent.com/1685008/37188075-58424d00-2388-11e8-8fa8-edc118c1b2db.png">

这段里面的“就如”有点难受

**Comment by hongbinzuo** [comment]
<img width="736" alt="2018-03-09 10 57 50" src="https://user-images.githubusercontent.com/1685008/37188180-c055217e-2388-11e8-9e44-f751900be596.png">

这段“新合约”那块格式有问题

**Comment by hongbinzuo** [comment]
翻译完成，已merge，使用其他issue track以后发现的问题。
