### ISSUE TITLE
翻译Julia.rst

### ISSUE THREAD

**Issue by hongbinzuo** [etherchina/solidity-doc-cn#21]

**Comment by riversyang** [comment]
@luokingfly Are U Chinese? Please refer to [translation_process](https://github.com/etherchina/solidity-doc-cn/blob/develop/translation_process.md)

**Comment by bobjiang** [comment]
You can find readme and wiki as reference in this repo.
If not clear, please send email bob@hiblock.net

thanks.

**Comment by oldcodeoberyn** [comment]
认领
