### ISSUE TITLE
Readme中的加入翻译团队链接点击之后是404错误

### ISSUE THREAD

**Issue by riversyang** [etherchina/solidity-doc-cn#6]
我有兴趣一起翻译，但……如题。@hongbinzuo

**Comment by hongbinzuo** [comment]
你好，我们的翻译团队开始组建，需要进行试译，请私信我您的微信号

**Comment by hongbinzuo** [comment]
好像不能私信，请发我邮件

**Comment by riversyang** [comment]
已进试译群。

**Comment by ysqi** [comment]
@hongbinzuo 需要将组织和团队设置为公开：
团队： https://github.com/orgs/etherchina/teams/solidity-translation-team/edit
